name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3

      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        uses: ./.github/actions/yarn-nm-install

      - name: Test library
        run: lerna run test

      - name: Typecheck library
        run: lerna run typecheck

      - name: Build library
        run: lerna run build --ignore website

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        uses: ./.github/actions/yarn-nm-install

      - name: Build library
        run: lerna run build --no-private

      - name: Git status
        run: git status --porcelain

      - name: Git diff
        run: git --no-pager diff

      - name: Run auto shipit
        run: yarn auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
